apiVersion: 1
datasources:
  - name: Thanos
    type: prometheus
    url: http://thanos_querier:10902
    uid: thanos
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpMethod: GET
    version: 1
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    uid: prometheus
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      httpMethod: GET
    version: 1
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: (?:traceID|trace_id)=(\w+)
          url: $${__value.raw}
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo-query:16686/
    access: proxy
    editable: false
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: [ 'job', 'instance' ]
    version: 1
